POST http://localhost:3000/users
Content-Type: application/json

{
    
      "email": "momo@mail.com",
      "password": "momo",
      "role": "ADMIN"
    }

###
GET http://localhost:3000/users/3

### GET All Users
GET http://localhost:3000/users

###
PATCH  http://localhost:3000/users/56
Content-Type: application/x-www-form-urlencoded

a=3987987&b=098980

###
DELETE http://localhost:3000/users/3